//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blogg
    {
        public System.Guid BloggId { get; set; }
        public string Text { get; set; }
        public string Category { get; set; }
        public System.Guid AppUserId { get; set; }
    
        public virtual AppUser AppUser { get; set; }
    }
}
