//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;

    public partial class Teams
    {
        public Teams(Guid id)
        {
            using (var db = new SupenEntities())
            {
                var repos = new TeamRepos();
                var team = repos.GetTeam(id);
                TeamId = id;
            }
        }
        public Teams()
        {

        }
        public System.Guid TeamId { get; set; }
        public string TeamName { get; set; }
    }
}
